# Generated by Django 2.2.17 on 2021-01-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('name', models.CharField(max_length=70, verbose_name='Advertiser Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('title', models.CharField(max_length=50, verbose_name='Ad Title')),
                ('img_URL', models.CharField(max_length=2000, verbose_name='Image Address')),
                ('link', models.CharField(max_length=2000, verbose_name='Link')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertiser_management.Advertiser', verbose_name='Advertiser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
