# Generated by Django 2.2.17 on 2021-02-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Hour')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_count', to='advertiser_management.Ad', verbose_name='Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdClickCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Hour')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_count', to='advertiser_management.Ad', verbose_name='Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
