# Generated by Django 2.2.17 on 2021-01-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='img_URL',
            new_name='image',
        ),
    ]
