# Generated by Django 2.2.17 on 2021-01-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_ad_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsReportView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.View')),
            ],
            options={
                'abstract': False,
            },
            bases=('advertiser_management.view',),
        ),
        migrations.RenameField(
            model_name='click',
            old_name='click_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='click_time',
            new_name='time',
        ),
    ]
