# Generated by Django 2.2.17 on 2021-01-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_auto_20210127_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsReportView',
        ),
    ]
