# Generated by Django 2.2.17 on 2021-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_delete_statisticsreportview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='time',
            field=models.DateTimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='view',
            name='time',
            field=models.DateTimeField(verbose_name='Time'),
        ),
    ]
